package:
  create:
    set:
      image_repository: "ghcr.io/defenseunicorns/leapfrogai/leapfrogai-ui"
      # x-release-please-start-version
      image_version: 0.3.0
      # x-release-please-end
      name: leapfrogai-ui
    max_package_size: "1000000000"
