package:
  create:
    set:
      image_repository: "ghcr.io/defenseunicorns/leapfrogai/leapfrogai-ui"
      image_version: 0.2.0
      name: leapfrogai-ui
    max_package_size: "1000000000"
  deploy:
    set:
      name: leapfrogai-ui
      image_repository: "ghcr.io/defenseunicorns/leapfrogai/leapfrogai-ui"
      image_version: 0.2.0
      limits_cpu: 0
      limits_memory: 0
      limits_gpu: 0
      requests_cpu: 0
      requests_memory: 0
      requests_gpu: 0