apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: leapfrog-ui
spec:
  gateways:
    - istio-system/leapfrog-ui
  hosts:
    - "*"
  http:
    - route:
        - destination:
            host: leapfrog-ui.leapfrog-ui.svc.cluster.local
            port:
              number: 3000
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: leapfrog-ui
  namespace: istio-system
spec:
  selector:
    app: tenant-ingressgateway
  servers:
    - hosts:
        - '*'
      port:
        name: http
        number: 8081
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
        - '*'
      port:
        name: https
        number: 8444
        protocol: HTTPS
      tls:
        credentialName: tenant-cert
        minProtocolVersion: TLSV1_3
        mode: SIMPLE