apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: leapfrog-ui
spec:
  gateways:
    - istio-system/leapfrogai
    - istio-system/tenant
  hosts:
    - "*"
  http:
    - route:
        - destination:
            host: leapfrog-ui.leapfrog-ui.svc.cluster.local
            port:
              number: 3000