apiVersion: apps/v1
kind: Deployment
metadata:
  name: leapfrogai-ui
  namespace: leapfrogai
spec:
  selector:
    matchLabels:
      app: leapfrogai-ui
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: leapfrogai-ui
    spec:
      containers:
        - name: leapfrogai-ui
          image: {{ .Values.imageName }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            {{- toYaml .Values.envs | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
