apiVersion: v1
kind: ServiceAccount
metadata:
  name: leapfrogai-ui
  namespace: leapfrogai
---
apiVersion: v1
kind: Service
metadata:
  name: leapfrogai-ui
  namespace: leapfrogai
  labels:
    app: leapfrogai-ui
    service: leapfrogai-ui
spec:
  selector:
    app: leapfrogai-ui
  ports:
    - name: http
      port: {{ .Values.containerPort }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
