name: Publish Release Artifacts

on:
  push:
    tags:
      - "*"


jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Login to GHCR
      uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set VERSION
      run: echo "VERSION=$(git describe --abbrev=0 --tags | tail -n 1 | sed -e 's/^v//')" >> $GITHUB_ENV

    - name: Build leapfrogai-ui Image
      run: make docker-build VERSION=$VERSION

    - name: Publish leapfrogai-ui Image
      run: docker push ghcr.io/defenseunicorns/leapfrogai/leapfrogai-ui:$VERSION

    - name: Install Zarf
      uses: defenseunicorns/setup-zarf@f95763914e20e493bb5d45d63e30e17138f981d6 # v1.0.0

    - name: Build Zarf Package
      run: zarf package create . --set IMAGE_VERSION=$VERSION --confirm

    - name: Publish Zarf Package
      run: zarf package publish zarf-package-*.zst oci://ghcr.io/defenseunicorns/packages
